name: AWS ECS CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Correct AWS region here
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1     # âœ” CHANGED (your ECR region)

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Docker image
        run: |
          IMAGE_REPO=${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG=${GITHUB_SHA}

          echo "Using REPO: $IMAGE_REPO"
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker tag $IMAGE_REPO:$IMAGE_TAG $IMAGE_REPO:latest

          docker push $IMAGE_REPO:$IMAGE_TAG
          docker push $IMAGE_REPO:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs-task.json
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
